baseurl: /sfd2013

markdown:         rdiscount
pygments:         true
paginate:         4

title:            QDLUG | CoYouth Club
url:              http://qdlug.github.com/sfd2013

indexContent:     true

style:            /css/style.css
siteName:         SFD2013
siteDesc:         Software Freedom Day
favicon:          /favicon.ico
theme:            blue

copyright:        Copyright © 2011-2012 QDLUG All rights reserved.

eventDate:        2013/09/21 # 日期写得往后一天, 这样到当天的时候倒计时会才显示0天
siteNotice:       经过各位的努力, 2013 年SFD活动青岛站已于 9 月 21 日在中国海洋大学举行.
wikiurl:          http://wiki.softwarefreedomday.org/2013/China/Qingdao/CoYouth_Club/Home
statisticsCode:   <script>  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');  ga('create', 'UA-43702067-1', 'qdlug.github.io');  ga('send', 'pageview');</script>
